---
name: Pytest code testing

on:
  push:
  pull_request:

jobs:
  test_code:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-mock
        pip install -r requirements.txt
    - name: Analysing the code with pylint
      run: |
        cp config.py.example config.py
        pytest tests
